### ISSUE TITLE
createInvoice() does not create finalized invoice

### ISSUE THREAD

**Issue by joeried** [elbstack/lexoffice-client-js#7]
I think I found a bug in the `createInvoice()` method. The flag `finalized` does not have the desired effect. Instead, the invoice is only created as a draft.

As far as I can tell, this is because this `finalized` parameter is also sent to lexoffice API with this name. However, the name of the query parameter should be `finalize`.

**Comment by AnnaelleRoessert** [comment]
Thank you very much, it should be fixed now :)
