### ISSUE TITLE
DocumentField type seems to be incorrect

### ISSUE THREAD

**Issue by joeried** [elbstack/lexoffice-client-js#8]
I'm not completely sure, but I think the DocumentFileId type is wrong.
It is defined as 

```ts
export type DocumentFileId = Required<Partial<Invoice>, 'files'>;
```

The type definition directly below it, looks correct to me (though that line of code is commented out).

```ts
// export type DocumentFileId = {documentFileId:string;}
```

**Comment by AnnaelleRoessert** [comment]
Thank you twice, i implemented your suggestion :)
