### ISSUE TITLE
Issues with data returned by downloadFile()

### ISSUE THREAD

**Issue by joeried** [elbstack/lexoffice-client-js#9]
I'm not sure if this is a error in the library or if I just need to handle the returned data differently.

When I save what I get returned on an invoice download, I get a PDF that doesn't show me any errors when opened, but the content is just a blank page.

I think with this request you would have to use `responseType: 'arraybuffer'` because the expected response contains binary data. With this change the request works for me and I successfully get back a working PDF.

Am I doing something wrong here or is it actually due to the missing `responseType`?

**Comment by pReya** [comment]
@joeried The suggested `responseType: 'arraybuffer'` is not a Header or body property that gets forwarded to the API – so it won't change, what the API returns. This is a parameter for Axios, which will treat the returned value differently depending on this setting. I think it depends on what you want to do with the result of the call. In some cases `responseType: 'arraybuffer'` might be necessary, in other cases it might not. Can you show your code example, what/how you're trying to download/view  the file?

**Comment by AnnaelleRoessert** [comment]
in the latest release your change is implemented, thank you for the remark!
